baseurl: ""
url: "http://ok.nickvorobiov.com"
markdown: kramdown
exclude:
  - node_modules
  - package.json
  - README.md
  - gulpfile.js

title: "Помогу привлечь 5 клиентов за 5 дней"
description: "Предлагаю тебе упаковать своё предложение и быстро привлечь первых клиентов. Дам конкретные задания и рекомендации, которые позволят прямо сейчас получить деньги. Пойдёшь и используешь, получишь 5 клиентов в свой бизнес. На каждом шаге получаешь обратную связь. Действуем до результата, даже если не получится сразу, будем пробовать ещё."
keywords: "бизнес, стартап, тестирование ниши, выбор ниши, предприниматель, запуск"
author: "Николай Воробьёв"

permalink: /:title/

vk_app_id: 5640654 # localhost:8000
yandex_metrika: 40115875 # ok.nickvorobiov.com
google_analytics: UA-46456269-19 # ok.nickvorobiov.com
facebook_pixel_id: 1587051131601822
vk_retarget_url: '//vk.com/rtrg?r=aI/cf96k7qEjmzkRwyCoepI*VE4WUyEb51Uz28eKre3V1f*mGxHhj7qptg2mJ6ZJpz2Jm7G16svwZHBWjPliAz0fD25AfUBGNaCgf2CBkpewuwZLZJAWF6*ebILE68KYTswPvPwzat/KaGZrdnrXWoDjyj/4yAiEGQ*BDXRewFw-&pixel_id=1000027749'
