baseurl: ""
url: "http://ok.nickvorobiov.com"
markdown: kramdown
exclude:
  - node_modules
  - package.json
  - README.md
  - gulpfile.js
  - deploy
  - deploy-key.enc
  - deploy-key

title: "Помогу привлечь 10 клиентов за две недели"
description: "Предлагаю тебе упаковать своё предложение и быстро привлечь первых клиентов. Дам конкретные задания и рекомендации, которые позволят прямо сейчас получить деньги. Пойдёшь и используешь, получишь 5 клиентов в свой бизнес. На каждом шаге получаешь обратную связь. Действуем до результата, даже если не получится сразу, будем пробовать ещё."
keywords: "бизнес, стартап, тестирование ниши, выбор ниши, предприниматель, запуск"
author: "Николай Воробьёв"

permalink: /:title/

vk_app_id: 5693193 # ok.nickvorobiov.com
yandex_metrika: 40526720 # ok.nickvorobiov.com – 2
google_analytics: UA-46456269-23 # ok.nickvorobiov.com – 2
facebook_pixel_id: 1064201373633710
vk_retarget_url: '//vk.com/rtrg?r=ECu6fz0K2fYVqkiHRMnq1uz3az5w5NCKoWvSST2PIFP2LAPAh2YwRe7OJEJycb43grlqVkVpA3Kk1b7KIXnu5k69Fwu022rNuxel4FyGHhJt10G1JplRxFW1ALHwonSXD9syUwn5MD0DUWetbExFGjJbJ5eZayP*FV8UWGVjLRE-&pixel_id=1000035015'